### PR TITLE
Disambiguate config files from textures

### PR DESCRIPTION
**Pull request by neofright**
MS Dash config files are INI files. Let's give them a file extension that better matches their contents.

### CODE REVIEW

**Comment by MrMilenko** [comment]
We'll test this as its been discussed, the issue was some areas of the dashboard would not view anything beyond an XBX. This was changed in source mods, and later dash mods, and is pretty much a legacy thing at this point. Going to keep this open for now.

**Comment by neofright** [comment]
I just setup a build environment and compiled the dash. I can confirm that the dash reads the files with `.ini` extension absolutely fine with Rocky5's latest patches.

**Comment by Rocky5** [comment]
Doesn't the script work on linux/Mac?
I already fixed the paths + a couple other things. 

Guess I need to load up ubuntu lol

edit:
[Just ran in on Ubuntu 22.04.4 LTS & works fine, though the resize window and colour stuff doesn’t work. Will fix that.](https://github.com/OfficialTeamUIX/UIX-Lite/commit/64b592e121d7836727f030a39210ce91a9a3ca95)

**Review by Rocky5 — CHANGES_REQUESTED** [review]
This is fixed on the latest commit.
https://github.com/OfficialTeamUIX/UIX-Lite/tree/Rocky5-Edits

So if you can amend it that would be great, thank you. (not sure if it will cause issues when mine is merged)

this, man a hate github lol
https://github.com/OfficialTeamUIX/UIX-Lite/pull/33/commits/e0d93f21c03550e9cc6256acac8e9596a3407b56

**Pull request closed without merging**
